lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: ~
    token_ttl: 3600 # 1 hora
    clock_skew: 0
    allow_no_expiration: false
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
    user_id_claim: email
